(cl:defpackage gps_navigation-msg
  (:use )
  (:export
   "<WAYPOINTACTION>"
   "WAYPOINTACTION"
   "<WAYPOINTACTIONFEEDBACK>"
   "WAYPOINTACTIONFEEDBACK"
   "<WAYPOINTACTIONGOAL>"
   "WAYPOINTACTIONGOAL"
   "<WAYPOINTACTIONRESULT>"
   "WAYPOINTACTIONRESULT"
   "<WAYPOINTFEEDBACK>"
   "WAYPOINTFEEDBACK"
   "<WAYPOINTGOAL>"
   "WAYPOINTGOAL"
   "<WAYPOINTRESULT>"
   "WAYPOINTRESULT"
  ))

