; Auto-generated. Do not edit!


(cl:in-package gps_navigation-msg)


;//! \htmlinclude WaypointFeedback.msg.html

(cl:defclass <WaypointFeedback> (roslisp-msg-protocol:ros-message)
  ((distance
    :reader distance
    :initarg :distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass WaypointFeedback (<WaypointFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WaypointFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WaypointFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gps_navigation-msg:<WaypointFeedback> is deprecated: use gps_navigation-msg:WaypointFeedback instead.")))

(cl:ensure-generic-function 'distance-val :lambda-list '(m))
(cl:defmethod distance-val ((m <WaypointFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gps_navigation-msg:distance-val is deprecated.  Use gps_navigation-msg:distance instead.")
  (distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WaypointFeedback>) ostream)
  "Serializes a message object of type '<WaypointFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WaypointFeedback>) istream)
  "Deserializes a message object of type '<WaypointFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WaypointFeedback>)))
  "Returns string type for a message object of type '<WaypointFeedback>"
  "gps_navigation/WaypointFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WaypointFeedback)))
  "Returns string type for a message object of type 'WaypointFeedback"
  "gps_navigation/WaypointFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WaypointFeedback>)))
  "Returns md5sum for a message object of type '<WaypointFeedback>"
  "acff7fda0c683c872875f5c4b069f124")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WaypointFeedback)))
  "Returns md5sum for a message object of type 'WaypointFeedback"
  "acff7fda0c683c872875f5c4b069f124")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WaypointFeedback>)))
  "Returns full string definition for message of type '<WaypointFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%float64 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WaypointFeedback)))
  "Returns full string definition for message of type 'WaypointFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%float64 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WaypointFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WaypointFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'WaypointFeedback
    (cl:cons ':distance (distance msg))
))
