; Auto-generated. Do not edit!


(cl:in-package gps_navigation-msg)


;//! \htmlinclude WaypointResult.msg.html

(cl:defclass <WaypointResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass WaypointResult (<WaypointResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WaypointResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WaypointResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gps_navigation-msg:<WaypointResult> is deprecated: use gps_navigation-msg:WaypointResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <WaypointResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gps_navigation-msg:success-val is deprecated.  Use gps_navigation-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WaypointResult>) ostream)
  "Serializes a message object of type '<WaypointResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WaypointResult>) istream)
  "Deserializes a message object of type '<WaypointResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WaypointResult>)))
  "Returns string type for a message object of type '<WaypointResult>"
  "gps_navigation/WaypointResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WaypointResult)))
  "Returns string type for a message object of type 'WaypointResult"
  "gps_navigation/WaypointResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WaypointResult>)))
  "Returns md5sum for a message object of type '<WaypointResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WaypointResult)))
  "Returns md5sum for a message object of type 'WaypointResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WaypointResult>)))
  "Returns full string definition for message of type '<WaypointResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WaypointResult)))
  "Returns full string definition for message of type 'WaypointResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WaypointResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WaypointResult>))
  "Converts a ROS message object to a list"
  (cl:list 'WaypointResult
    (cl:cons ':success (success msg))
))
