// Generated by gencpp from file gps_navigation/WaypointFeedback.msg
// DO NOT EDIT!


#ifndef GPS_NAVIGATION_MESSAGE_WAYPOINTFEEDBACK_H
#define GPS_NAVIGATION_MESSAGE_WAYPOINTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gps_navigation
{
template <class ContainerAllocator>
struct WaypointFeedback_
{
  typedef WaypointFeedback_<ContainerAllocator> Type;

  WaypointFeedback_()
    : distance(0.0)  {
    }
  WaypointFeedback_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::gps_navigation::WaypointFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps_navigation::WaypointFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointFeedback_

typedef ::gps_navigation::WaypointFeedback_<std::allocator<void> > WaypointFeedback;

typedef boost::shared_ptr< ::gps_navigation::WaypointFeedback > WaypointFeedbackPtr;
typedef boost::shared_ptr< ::gps_navigation::WaypointFeedback const> WaypointFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps_navigation::WaypointFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gps_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'gps_navigation': ['/home/user/catkin_ws/devel/share/gps_navigation/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_navigation::WaypointFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_navigation::WaypointFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_navigation::WaypointFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::gps_navigation::WaypointFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps_navigation/WaypointFeedback";
  }

  static const char* value(const ::gps_navigation::WaypointFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback\n\
float64 distance\n\
\n\
";
  }

  static const char* value(const ::gps_navigation::WaypointFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps_navigation::WaypointFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps_navigation::WaypointFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_NAVIGATION_MESSAGE_WAYPOINTFEEDBACK_H
